name: pylint
on: [push]
jobs:
  run-pylint:
    name: Run-pylint
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install pansat package
        run: pip install .
      - name: Install pylint
        run: pip install pylint
      - name: Lint Code Base
        run: pylint pansat
