name: weekly build
on:
  push:
    branches:
      main
jobs:
  install_and_test_job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/weekly_build
        env:
          PANSAT_PASSWORD: ${{ secrets.PANSAT_PASSWORD }}
          PANSAT_LOG_LEVEL: DEBUG

